# Generated by Django 4.2 on 2024-07-04 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=8)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
