# Generated by Django 4.2 on 2024-07-10 02:42

from django.db import migrations, models
import tickets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dni',
            field=models.CharField(max_length=10, validators=[tickets.utils.valida_cedula]),
        ),
    ]
